### ISSUE TITLE
Search by discid against various artists with multiple releases does not return artists on tracks for second or later release

### ISSUE THREAD

**Issue by jrvjrv** [bfaist/webservice-musicbrainz#4]
A query by discid for a disc with multiple releases on a disc with multiple artists returns artists on the tracks of the first release but not on the second and following releases. See https://community.metabrainz.org/t/abcde-not-working-correctly-with-multiple-releases-and-various-artists/135740 for more details.

The first release has artists:

```
<track-list>
  <track id="e7097679-946f-433b-87ce-16745260ca04">
    <title>The Djinni</title>
    <duration>282200</duration>
    <artist id="ba08e074-e813-46b7-afc0-e9135adee444">
      <name>DJ JD</name>
      <sort-name>DJ JD</sort-name>
    </artist>
  </track>
  ... etc.

```

The second and following do not:

```
<track-list>
  <track id="e7097679-946f-433b-87ce-16745260ca04">
    <title>The Djinni</title>
    <duration>282200</duration>
  </track>
  ... etc.

```

Strictly speaking this is a defect in the musicbrainz api, but the defect is in version 1 of the api, which is long-deprecated and so probably will not be remedied in that api.

**Comment by bfaist** [comment]
Since the latest version of WebService::MusicBrainz is using the version 2 of the API, this is no longer an issue.  Added tests to Discid.t to check.
