### ISSUE TITLE
Bug on compiling under Xenial

### ISSUE THREAD

**Issue by mohahn** [bfaist/webservice-musicbrainz#8]
At the moment I do not have more information, sorry. But under Xenial (using Docker image `lsiobase/ubuntu:xenial`) compilation of latest source code fails on subtest in `t/Area.t` line 45. I run `make` without any special parameters. When commenting out line 45 in test file, build works. Is there any chance to tell me what this test means? Or are you able to re-produce this error?

Edit: This is related to https://github.com/bfaist/webservice-musicbrainz/pull/7

**Comment by bfaist** [comment]
Release 1.0.5 to CPAN with #7 merge request.
